/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Achievement map info
 */
export default class AchievementMapInfo {
  off_3: Resource = $r('app.media.ic_badge_3_off');
  on_3: Resource = $r('app.media.ic_badge_3_on');
  off_7: Resource = $r('app.media.ic_badge_7_off');
  on_7: Resource = $r('app.media.ic_badge_7_on');
  off_30: Resource = $r('app.media.ic_badge_30_off');
  on_30: Resource = $r('app.media.ic_badge_30_on');
  off_50: Resource = $r('app.media.ic_badge_50_off');
  on_50: Resource = $r('app.media.ic_badge_50_on');
  off_73: Resource = $r('app.media.ic_badge_73_off');
  on_73: Resource = $r('app.media.ic_badge_73_on');
  off_99: Resource = $r('app.media.ic_badge_99_off');
  on_99: Resource = $r('app.media.ic_badge_99_on');
  success_task1:Resource = $r('app.media.ic_task1_success');
  success_task2:Resource = $r('app.media.ic_task2_success');
  success_task3:Resource = $r('app.media.ic_task3_success');
  success_task4:Resource = $r('app.media.ic_task4_success');
  success_task5:Resource = $r('app.media.ic_task5_success');
  success_task6:Resource = $r('app.media.ic_task6_success');
  success_task7:Resource = $r('app.media.apple');
  undo_task1:Resource = $r('app.media.ic_task1_undo');
  undo_task2:Resource = $r('app.media.ic_task2_undo');
  undo_task3:Resource = $r('app.media.ic_task3_undo');
  undo_task4:Resource = $r('app.media.ic_task4_undo');
  undo_task5:Resource = $r('app.media.ic_task5_undo');
  undo_task6:Resource = $r('app.media.ic_task6_undo');
  undo_task7:Resource = $r('app.media.app_icon');

  statement_task_success: string[] =["起的真早啊！！",
    "多喝水对身体好，达成目标！！",
    "多吃苹果，医生远离我！！",
    "开心的一天啊！！",
    "我爱刷牙！！",
    "早睡达成，智力似乎在上涨！！",
    "跑步强身健体！"];

  task_name: string[] =["早起",
    "喝水",
    "吃果",
    "微笑",
    "刷牙",
    "早睡",
    "跑步"];
}
